### ISSUE TITLE
Invalid JSON format

### ISSUE THREAD

**Issue by Tobus** [pbek/qownnotesapi#1]
Hello,
when I'm trying to connect with the MyOwnNotes Android App I will get the error:

"Invalid JSON format"

With the Windows Desktop App all works fine.
Do you know what to do?
Best regards
Tobias

**Comment by pbek** [comment]
I'm sad to tell you that, I'm not the author of MyOwnNotes, nor do I own an Android phone. Maybe the Author can help you directly?

**Comment by pbek** [comment]
https://github.com/aykit/MyOwnNotes/issues

**Comment by Tobus** [comment]
What a android client do you prefer?

**Comment by pbek** [comment]
MyOwnNotes should work as it is directly communicating with ownCloud via WebDAV (I guess that is what MyOwnNotes is doing). I myself have an iPhone and use CloudNotes.
