### ISSUE TITLE
No Connection to QOwnnotesApi

### ISSUE THREAD

**Issue by Steakschen** [pbek/qownnotesapi#10]
Hey,

i istalled owncloud on my vserver but cant get a connection with the windows app.

Verbindung zum ownCloud Server konnte nicht hergestellt werden!
Die QOwnNotesAPI App muss installiert und aktiviert sein!
Fehlermeldung: Unbekannter Fehler

Connection to Webserver OK
User and Password OK
Connection to QOwnNotesAPI not connected.

I git cloned it into /owncloud/apps and startet it.

Cant figure out why it isnt working :(

**Comment by pbek** [comment]
Can you please post the output from the debug settings.
Did you enable the extension on your ownCloud server?

**Comment by pbek** [comment]
I will close this issue until there is more information.
