### ISSUE TITLE
QOwnNotes can't get note versions

### ISSUE THREAD

**Issue by benqrn** [pbek/qownnotesapi#11]
When running edit -> 'Show note versions', this appears in NC error log;

`OCP\Files\NotFoundException: /test.md not found while trying to get owner`

running QOwnNotes 17.03.4, NC 11.0.2 and QOwnNotesAPI 17.3.0.  NextCloud account is configured in the QOwnNotes settings and connects successfully, files are being synchronized with the official NC client.  QOwnNotes and the sync client are running on windows 7.

**Comment by pbek** [comment]
Do you have your server side note folder configured correctly in QON?

Am 13.03.2017 22:00 schrieb "benqrn" <notifications@github.com>:

**Comment by benqrn** [comment]
No, choosing a folder fixed it :)  Thanks.

'Notes' is already populated in the 'path on your server' box (though it is grey), so I assumed it was trying that folder as a default.  The UI should be changed to reflect that it does not try any folder by default, or at least display an error that no folder was selected.

**Comment by pbek** [comment]
## 17.03.6
- when configuring a new note folder path in the settings the server-path 
  will now be suggested
    - the placeholder text was changed to be more informative

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by benqrn** [comment]
The hint in the Note folder settings is much better, though if that field has to be set to view versions, there should be an error when clicking 'show note versions' instead of it saying 'There are no other versions on the server for this note.'

**Comment by pbek** [comment]
QOwnNotes doesn't really know that because it doesn't get that information.

**Comment by benqrn** [comment]
The path has to be set to **something** for show note versions to work; so I'm saying if the path is unset in the folder settings, an error should be shown instead of a misleading info box.

**Comment by pbek** [comment]
"nothing" is the oC / NC root path

**Comment by benqrn** [comment]
No one is going to store their notes in the user root folder.  The info box doesn't even say the actual error which is 'file not found', just says 'no previous versions.'  It's not telling the user what is actually happening.

**Comment by pbek** [comment]
## 17.03.7
- improved error messages for the version and trash dialog

There now is a new release, could you please test it and report if it works for you?
