### ISSUE TITLE
Certificate is not valid.

### ISSUE THREAD

**Issue by Laupe** [pbek/qownnotesapi#12]
Nextcloud 12

- qownnotesapi
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

**Comment by pbek** [comment]
Thank you for reporting, where did you get the qownnotesapi?

**Comment by Laupe** [comment]
![image](https://cloud.githubusercontent.com/assets/1008242/25853598/ad2d8e88-34cd-11e7-8c83-aa8d2151972c.png)

**Comment by pbek** [comment]
Thank you for the screenshot, but again: where did you get the qownnotesapi? from the Nextcloud store?
I'm not sure what NC 12 is doing in that regard, but the app is in the NC store and you can't even get an app release into the store without signing it correctly...

**Comment by pbek** [comment]
It's basically the same with https://github.com/pbek/ownbackup/issues/18...

**Comment by Laupe** [comment]
from the Nextcloud store

**Comment by pbek** [comment]
Maybe this is of some help: https://github.com/nextcloud/server/issues/4765
If anyone knows more about that `InvalidSignatureException` in Nextcloud 12 please let me know.

**Comment by Laupe** [comment]
So I deleted and reinstalled as instructed on https://github.com/nextcloud/server/issues/4765#issuecomment-300181935 and you write this error anyway so maybe an NC server error

**Comment by Laupe** [comment]
![image](https://cloud.githubusercontent.com/assets/1008242/25864461/c8908de8-34ef-11e7-969c-b8a947bb918f.png)

```
root@private:/home/apps/cloud/apps/qownnotesapi/appinfo# cat signature.json
{
    "hashes": {
        ".codeclimate.yml": "44305278cdce56e606693da0d3940fd26fd95465a26b1fb149c9510c3e66bdc6d16af3765cf3c6f8ca8dd867f8f4c9bfa6f26674b6912b979926a72eb6ab86f7",
        ".gitignore": "d5cc0283d4eb9d4adb7b11ef526d933fafc81e4a3c7191d2331ce6965170a7a1e7117aab69b730e4b25cf5354222230a72adb8a87fe60006929948217218537a",
        ".travis.yml": "1121cd6bcf2acf4833bf7bc024afc8b7885f47ab4f5afeec91e249845b239609bbca3fc6bc720e9c835dd01c1d23b97afa8830e6a7f0e42cb3ff6ddf0e01ecba",
        "3rdparty\/finediff\/finediff.php": "328d63a5a24fe36118dfb3c3acd01f7f88c6e89eef1d045270d4edfd3d048b70cb034888494c3cc435863034d72c71b0d6719932e902d962a71f51c376eb1bbd",
        "AUTHORS.md": "471173dfd8ee079c988b04ea7b12a7cab1d82bcc1491f8075b805ead2718fa3578fce4afb334244fb464bbc28b38f5a2b9c1d6403ee6866237832bdf7aca2e17",
        "CHANGELOG.md": "7ca1f8ed70e926a5a8a9307ae4fb9504498da13c87cbfac59b9eaab2f3b68f28e43574122b1a77a6bd1eb79a299ba05eebefefbff10f55191190c38843cfe944",
        "COPYING": "6e90d46be391aa645bcf4dfaa67f452cb15a73749f1895633789c7763b43cc0b65d391e5e95652c9a9a2063c956e0e8099a4e1ce4b70b0636629f9eac39c1080",
        "Makefile": "d2f61de81d762aaee5a5876798e702d513eb2ad80cd5e9a62ff256f4b88fb2f7da8876bd74ed7d20f2b95843d1de7c6eba155aaf1f9509029e3ec15b3256999a",
        "README.md": "0f5bc3a58884b9b039e8763f06cc99dd3ea048b43bf6bd23d61a4528fd763bf175d8157e51e9e1521752e4a9ed82c547685e569dda9d44e83fb88c35190e597b",
        "appinfo\/app.php": "3dad69fab4e6b4e44ff49b9d20f06ec974e40cd1132b43817e62555737a972b5d95f29b7c59a07c202135da4e273a814f4b70eda4525a51f3609919a1b72711c",
        "appinfo\/application.php": "827097b1ad8f7075534333582d0c8696098a59c26f09219cf0d03194e1559376fa5e210588e80678a2bf9081b918763502ed36757309568abb198cee5a30c1e1",
        "appinfo\/info.xml": "d69a1a7798dd576241d30189f712d3e3032333421da02cfcb5b03a118cdce9f363a6c9bb699f38f25d218b1800275145a356cada77af0126e05d06e7bf46be61",
        "appinfo\/routes.php": "fd68b2f22cd76805e12502a36edcfd1532592df821ff0b582af9bb94d1974cacfe962226d34376285f5b9ad7c61ffaf283e02cdc8aa72b49845f61ecf7cd09fb",
        "controller\/noteapicontroller.php": "b5f641b2b29f5fe542eb6381ea34e9c1f74112bd2a0b4915bc59429a0b225c1218bc2744570dbc288e860d7cea72863f49b240ebc1a5adc442be55001a105ddd",
        "img\/app.svg": "3518a23d17ef9ff18ea73c96e0f382bb439436ca15383495926563d821e293eec44ce90d397a508b21fde12e40db72022081ffc954e5cd34ed992d3cbeb04171",
        "lib\/capabilities.php": "e1bf7d12d324f9378e317435da9fa646d7d565b84f4236491cb2cd5549abcc7e226f4f49bfdfb5ec7bf112a67a6adafae588c32692447fb9e9f837eae1b06b43",
        "phpunit.coverage.xml": "21686e83eada96dd35b0187b5f9e5f4df15e9ab0faf36c54c8cc1f0631f739f56bbccb1a0668002ebb13104d7e28ecfec9b277ca665641b3abab4330a12dddca",
        "phpunit.integration.xml": "d477d2d4e122ea372352b7e3c96e6973ad6c82b04c3adeb1edf02029f1cff62240ac188b99e063c7423e7603098dd7ab89c8f146c5382d8c8a9e0a9117f70da3",
        "phpunit.xml": "c4b7fe8203adf562ae2aa01090b46d0a1337df7766285b97d5fe27be19636f5385deb08f19101305536423006deed50eb22f3cc7f6ebf5c1d2fc4fe009c961bc",
        "screenshot.png": "45d7ed1c40c52c709271e89c0360229469f4371eeac1ee72fbae52796d4b7cc20093589f369498d3aff699875cac160a073230ac4d8cbc345f770617535f89ce",
        "tests\/integration\/AppTest.php": "6ab2b514e3abcdd947f10bdd53e548581bfdaf9cb13fc622860c23907cbeaa999ba472bb243c0812e98766ab8025c2447d5a2ddfaf4a7573483691b8a34ea478",
        "tests\/travis\/php.ini": "42ae4f728eb4e0cec696ae48c61d58e50e836b0f291cf74fdc0d7229c565c2bf3c076ac150ce7250dde2e4600804f17404a09555e1978d7e79bb84d39e2c78e1",
        "tests\/unit\/controller\/NoteApiControllerTest.php": "32547a819015a7c446eddc27e232fec28107b3ca5037080f7c31f420756ed19497f89bc1c1e3c47e5d43496c599bed991f8640222216c191d76fc9247f6a84b7"
    },
    "signature": "SZVVp+52xH7sXydEYQ\/YFSl3t6W26mFUoXqIr6JSvYkNSf\/evuWQx\/51rkVUIYNoubJWyxJeRHV\/Zusbnq+C5BLdejISRnD1TmieTifqHCIIsZ1EQe7O\/unOjUviebIKofyaUNB8+Ft\/sioOvMyL14SCJ33gz0MecHbz2O\/nWltDCZGRHQPKa0xrPc2X\/pqIea0zOXYQLWLkWL0Nkyp6YsUQrPBPr6w8Ip6bPw6QGTaY8zn7niVfYIOILwRgxYRPGuxg1wfWPf\/nlJYWNDrN8S4L9O0f9wV5aWaYE+cVf7Lfip1Ku1j3cTTktYwdnwZICLJo7SC+2go00hnCLc2Trw==",
    "certificate": "-----BEGIN CERTIFICATE-----\r\nMIID+TCCAeECAhAJMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD\r\nVQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93\r\nbkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE2\r\nMDYwODE2MDgwM1oXDTI2MDYwNjE2MDgwM1owFzEVMBMGA1UEAwwMcW93bm5vdGVz\r\nYXBpMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6RusKtWJc8BncwJL\r\n2Vy0OSAjhSxnuLvzVxJh4uWHgmdylewTVPlBcVAVwG8SqkrbHg37bTKZ9Rpiqn4p\r\nwHY6SQM\/3T6Y58yzLWDQjW6QaGCVwl42cPM+1coi6IxNJc7LhyTjomcSaKLQJTEQ\r\nWCFrmLod2y3xCzzTFYV2cxDMZ0i7JZNjejJ2me9YIcITsAGl3i+IFRnxzjf42qWx\r\n0ZmO7CoGQKLJGuSM99nLWUwZZdAMxTmliIYigqkw6acn6dZ2m6CLfriqPjHGqLiT\r\nYJuuk3+WSNSSzeF62TdUS4YsL+8Mj9yC6LAy+PyOeSF1agZc5k+IPcpXpGefU1P4\r\ntm56IQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAw2cxskDJyp98+Nbd4PKmvwB8f\r\nUCDhN4xQSVAYHzweSP6ejRkH4mMCiE39cMP5uEBq3q6jxOFWYbT6pq7+6EzBhB4a\r\n+ycWhbTOXntSRz5XJChOju4JEQcGqNhc4R1FX0OnJEPZeaN+KL6JVqSz77Hq7Pzk\r\nm9MTGbHSFbYjNMkg\/nVjfV+ov1PC8bbYeWCflGwMRA2R12hbMhfMZx0C4SVdk6pb\r\nFgDOyBc9cwGcCTIvXLK1NXUbigMiZJxMhLhvLY03PF0FcMhn341k6\/KHcZ28F4Lz\r\n+loBa0d2q+SY8ELV7H4WGzRUK9bjIm81EehH0tMF5aKu3ZNIjP3Ppr2DsXTATwW2\r\nCSF7KRm1WByimZjiU9OfQHQPOQjDNZz9ZcV2tGy74w8cSjpocxmBTHu1WtB\/LJ7J\r\nfsHY83EmCTquOE99YBGwIGfONgeDuf33DH9vx6lob\/XrWfoSKAXQm7HphQc2HklP\r\niwZQIAyxPACzUlo6pEiFG\/HxRycqigHQI+7mLfUERG+x1IHxIEW+0jgXmrpl0607\r\nk54ZKD+duwPYH3W0MtQDEt\/rQxEk0qVTFNBh3hHinNUx4apuSrX9pRB1knKW6Gok\r\nM\/+snzqZ5EpRD7VwFm5oxSV+Jw\/krjXZm06P13sUkCPcQIa\/aS1r3xwPNhK39iNV\r\nfBfTytCoI\/Dp7H7tPw==\r\n-----END CERTIFICATE-----"

```

App store returns badly signed archives

**Comment by Laupe** [comment]
@pbek I know where the bug is! The bug is in your application.

A purely installed cloud, and the only allowed application ownbackup reports this error when you go into the additional settings

`{"reqId":"bw6zJpDS7UuuoGG9kHeY","level":3,"time":"2017-05-09T18:12:09+00:00","remoteAddr":"80.95.253.60","user":"Laupe","app":"index","method":"GET","url":"\/settings\/admin\/additional","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve AppName! Class AppName does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('AppName')\\n#1 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AppName')\\n#2 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(66): OC\\\\ServerContainer->query('AppName')\\n#3 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\OwnBackup\\\\\\\\C...')\\n#5 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\OwnBackup\\\\\\\\C...')\\n#6 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(410): OC\\\\ServerContainer->query('\\\\\\\\OCA\\\\\\\\OwnBackup\\\\\\\\...')\\n#7 \\\/home\\\/apps\\\/cloud\\\/apps\\\/ownbackup\\\/admin.php(19): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('\\\\\\\\OCA\\\\\\\\OwnBackup\\\\\\\\...')\\n#8 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/legacy\\\/app.php(727): include('\\\/home\\\/apps\\\/clou...')\\n#9 \\\/home\\\/apps\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(102): OC_App::getForms('admin')\\n#10 \\\/home\\\/apps\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(93): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getLegacyForms()\\n#11 \\\/home\\\/apps\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(73): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getSettings('additional')\\n#12 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('additional')\\n#13 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#14 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#15 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#16 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('AdminSettingsCo...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#19 \\\/home\\\/apps\\\/cloud\\\/lib\\\/base.php(976): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin...')\\n#20 \\\/home\\\/apps\\\/cloud\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/home\\\/apps\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Mozilla\/5.0 (Windows NT 6.3; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/57.0.2987.133 Safari\/537.36","version":"12.0.0.16"}
`

**Comment by pbek** [comment]
How could it be a bug in the application if nothing was changed and it works in NC 11?

**Comment by Laupe** [comment]
@pbek Look at https://docs.nextcloud.com/server/12/developer_manual/app/settings.html

https://github.com/pbek/ownbackup/blob/develop/appinfo/routes.php#L19

``` php
['name' => 'admin#do_restore_tables', 'url' => '/restore-tables', 'verb' => 'POST']
```

It should be something like
``` php
['name' => 'settings#admin', 'url' => '/settings', 'verb' => 'POST']
```

There is some change. I did not study it very much, but I looked into other applications as it solves to write information to settings and do it differently.

Look
https://github.com/nextcloud/server/blob/master/apps/updatenotification/appinfo/info.xml#L19
https://github.com/nextcloud/server/blob/master/apps/updatenotification/appinfo/routes.php#L28

**Comment by pbek** [comment]
thank you for your research, @Laupe

**Comment by pbek** [comment]
@Laupe I guess your comment about the routes was meant for ownbackup, right? qownnotesapi has no admin page...

**Comment by pbek** [comment]
Can you please create an issue for that...

**Comment by pbek** [comment]
But I still have no clue what is causing the `OC\IntegrityCheck\Exceptions\InvalidSignatureException` in both apps...

**Comment by Laupe** [comment]
@pbek Yes it was on ownbackup - Regarding the problem of ownbackup I will write in the issue you sent

[OC\IntegrityCheck\Exceptions\InvalidSignatureException](url)
I think you're badly certifying those applications

**Comment by pbek** [comment]
You don't get "badly signed" applications in the NC store...

**Comment by awlx** [comment]
I see the same with Nextcloud 12 stable ...
php occ integrity:check-app qownnotesapi
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Certificate is not valid.

**Comment by pbek** [comment]
Yes, it's not 100% what needs to be done in the future. Please see: <https://github.com/nextcloud/server/issues/4852>

**Comment by enoch85** [comment]
I can confirm this on Nextcloud 12 with the App installed from the Nextcloud store.

**Comment by pbek** [comment]
I now released a new version of the app into the NC store that was signed with a NC certificate. Does that work for you? (You will have to reinstall the app.)

**Comment by Laupe** [comment]
@pbek I confirm, just reinstall the application (Disable, Delete, Install again from the app store) and all is fine! Thanks for the resolution.

**Comment by enoch85** [comment]
Works for me as well! Thanks.Best regardsDaniel HanssonTech and MeSent from mobile, sorry for typos.Den 23 maj 2017 4:48 em skrev Pavel Dvořák <notifications@github.com>:@pbek I confirm, just reinstall the application (Disable, Delete, Install again from the app store) and all is fine! Thanks for the resolution.

**Comment by pbek** [comment]
Great, thank you for testing!

**Comment by jpaechnatz** [comment]
Disabled, deleted, downloaded nc app store version.

Download from nc app store:
sha256sum:
2bff62d0e810376d2084ac02b79af0f2bfcb38c2390f6227326669edf4b66db7  qownnotesapi-nc.tar.gz
Version 17.5.0 - Does NOT work with nextcloud 12.0.1

Disabled, deleted and installed via git as stated in Administrator Documentation - does NOT work too.

:-(

Any Ideas?

**Comment by pbek** [comment]
did you delete it directly on your filesystem on your server? maybe not everything was removed...

**Comment by jpaechnatz** [comment]
I checked the apps directory between each try if everything is removed correctly - so yes, uninstall is working. ;-)

**Comment by pbek** [comment]
Then I frankly have no idea. :/
This is the release that was accepted by the NC app store: <https://github.com/pbek/qownnotesapi/releases/tag/17.5.0-nc>

**Comment by pbek** [comment]
@jpaechnatz maybe the last comment in #15 helps you
