### ISSUE TITLE
Certificate invalid

### ISSUE THREAD

**Issue by Gerii** [pbek/qownnotesapi#13]
After upgrading to Nextcloud 12, I get the following error with qownnotesapi 17.5.0:
```
- qownnotesapi
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
```

**Comment by pbek** [comment]
Please reinstall the app from the NC store. (see #12)

**Comment by Gerii** [comment]
Thanks, should have looked at the closed issues.
