### ISSUE TITLE
nextcloud 12.0.1 - Certificate is not valid

### ISSUE THREAD

**Issue by jpaechnatz** [pbek/qownnotesapi#14]
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- qownnotesapi
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [qownnotesapi] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)

**Comment by pbek** [comment]
Please reinstall the app from the NC store. (see #12)
