### ISSUE TITLE
Integrity test for qownnotesapi fails after update to Nextcloud 12.01

### ISSUE THREAD

**Issue by bugzy** [pbek/qownnotesapi#15]
After update to Nextcloud 12.01, I get a notification in the admin console stating "Some files have not passed the integrity check." When I choose the option for more information, I get the following

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- qownnotesapi
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [qownnotesapi] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)

**Comment by pbek** [comment]
Did you update NC from 12 to 12.01?

Nothing has changed to the app, it was signed with the NC certificate and there were no changes done to the app in the store...

Can you please post your issue to <https://github.com/nextcloud/server/issues> if your were updating from NC 12.

**Comment by emansije** [comment]
I have the same issue and I'm using the stable channel, meaning that I went from version 11.x.y to 12.0.1. Would reinstalling qownnotesapi solve the issue?

**Comment by pbek** [comment]
yes, for updates from pre-NC12 please see #12, they removed their old root cert...

**Comment by bugzy** [comment]
I also went from 11.0.3 to 12.0.1. disabling, removing, and then reenabling does not change the situation for me. Any luck @emansije ?

**Comment by bugzy** [comment]
I take that back. After disabling, removing, and then reenabling, you will need to hit rescan on the code integrity check line for the error to go away.

**Comment by pbek** [comment]
thank you, @bugzy!

**Comment by jpaechnatz** [comment]
Worked. Disable, remove, enable rescan via webinterface! occ app:check-code qownnotesapi reported everything ok, but webinterface was still showing an error. After rescan it works again.

Thanks

**Comment by emansije** [comment]
It worked for me too. I first tried to simply disable and enable it, followed by a rescan, but that didn't change anything. I had to do the complete disable-uninstall-install cycle and then do a rescan to make the warning go away.

**Comment by rakekniven** [comment]
One more confirmation 👍
