### ISSUE TITLE
Documentation about postgreSQL

### ISSUE THREAD

**Issue by aventrax** [pbek/qownnotesapi#16]
Hello, probably I'm on the wrong place but I can't find a way to contact you.
I'd want to ask if postgreSQL is supported because I'm planning to convert my NC installation to it.
Many thanks.

**Comment by pbek** [comment]
I've never tested it, except with my automated tests via TravisCI.
It should work because the NC Database APIs are used.

**Comment by aventrax** [comment]
Thanks!

**Comment by aventrax** [comment]
I confirm it's working properly. Thanks.

**Comment by pbek** [comment]
Thank you for letting us know!
