### ISSUE TITLE
ownCloud marketplace shows version 17.7.0. This release does not exists here.

### ISSUE THREAD

**Issue by rakekniven** [pbek/qownnotesapi#19]
Just seen v17.7.0 at https://marketplace.owncloud.com/apps/qownnotesapi

Is this an official release?

**Comment by pbek** [comment]
Yes

**Comment by pbek** [comment]
See: https://github.com/pbek/qownnotesapi/blob/develop/CHANGELOG.md ;)

**Comment by rakekniven** [comment]
Oh, thank you for pointing me to your well maintained changelog. First I checked releases at https://github.com/pbek/qownnotesapi/releases and missed it.

**Comment by pbek** [comment]
I needed a new version to trigger the update in ownCloud.
