### ISSUE TITLE
How can I remove qownnotesapi?

### ISSUE THREAD

**Issue by adam-szabo** [pbek/qownnotesapi#22]
My nextcloud complains about invalid signature in qownnotesapi:

```
- qownnotesapi
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.d.
```

How can I remove this app from Nextcloud?

**Comment by pbek** [comment]
Please reinstall the app from the NC store. (see #12)
