### ISSUE TITLE
Can't get Nextcloud sync to work

### ISSUE THREAD

**Issue by danbohea** [pbek/qownnotesapi#24]
Just installed Nextcloud for the first time today and I can't get notes to sync in either direction despite QOwnNotes confirming a successful connection:

```
The connection was made successfully!
Server version: 15.0.5.3
QOwnNotesAPI version: 18.11.0
```
I installed Nextcloud via `snap` - not sure if that's an issue?

**Comment by pbek** [comment]
maybe https://www.qownnotes.org/Knowledge-base/Why-isn-t-QOwnNotesAPI-syncing-my-notes helps :)

**Comment by danbohea** [comment]
Thanks for the link. I guess that narrows things down to it more likely being an issue with the Nextcloud desktop client than with qownnotesapi.
