### ISSUE TITLE
Support Nextcloud authentication via app token

### ISSUE THREAD

**Issue by danbohea** [pbek/qownnotesapi#25]
QON API can no longer connect if I install and enable the Nextcloud twofactor_totp app:

![image](https://user-images.githubusercontent.com/6885065/55873144-c2980a00-5b86-11e9-846d-f5784a164523.png)

I'm guessing that this is because QON API is only attempting to connect with user credentials. The Nextcloud mobile & desktop apps seem to get round this by providing a means to authenticate via application token. Could support for this be added to QON API? It's a real shame that I have to trade security for features/convenience with the current situation.

**Comment by pbek** [comment]
You can create an "app password" on <https://your-server/settings/user/security>.

Does this answer your question?

**Comment by danbohea** [comment]
Yeah, that's what I meant by app token. So are you saying that I can use that generated user/pass in the form in QON API?

**Comment by pbek** [comment]
Yes

**Comment by danbohea** [comment]
Face-palm. I don't know why that didn't occur to me. Thanks!
