### ISSUE TITLE
Adding secondary Todo Nextcloud Calendar via "Other CalDAV Server"

### ISSUE THREAD

**Issue by sunjam** [pbek/qownnotesapi#27]
Hi, I'm attempting to add todos using _Other CalDAV Server_ for a remote Nextcloud instance that does not have QownnotesAPI installed.

Remote server is running Tasks and Calendars apps.

I added the Calendar base url as _Primary CalDAV address_ listed in Nextcloud calendar app.
Reads as `https://cloud.example.com/remote.php/dav/`
Added user name and one time password.

I select _Reload calendar list_, but no calendars or tasks show up despite having multiple available from the webui.

Thanks!

**Comment by pbek** [comment]
have you closed this on purpose?

**Comment by sunjam** [comment]
Closed as I realized [the application has a different repo.  Issue filed there](https://github.com/pbek/QOwnNotes/issues/1196).
