### ISSUE TITLE
Error on updating Nextcloud 16 - compatibility issue

### ISSUE THREAD

**Issue by jjisnow** [pbek/qownnotesapi#29]
Error message:
App "QOwnNotesAPI" cannot be installed because it is not compatible with this version of the server

Commands:
git clone https://github.com/pbek/oqnwnotesapi.git /var/www/nextcloud/apps/qownnotesapi -b master
sudo -u www-data php occ app:enable qownnotesapi

**Comment by jjisnow** [comment]
Fixed:
I ended up following your develop branch:

    cd /var/www/nextcloud/apps/qownnotesapi
    git checkout develop

Then in the nextcloud web profile -> apps -> qownnotesapi -> enable.

**Comment by pbek** [comment]
why don't you just install it from the ownCloud / Nextcloud marketplace?

**Comment by jjisnow** [comment]
Because from the marketplace, i simply get a 19.4 version as a   .tar.gz.
File, and the apps option on my server tells me there are no apps that
match my version

**Comment by pbek** [comment]
That's strange, because https://apps.nextcloud.com/apps/qownnotesapi says it's compatible with NC 16 and the store detects the version automatically from https://github.com/pbek/qownnotesapi/blob/develop/appinfo/info.xml

**Comment by jjisnow** [comment]
Thanks, couldn't install it directly from the local instance, but the download instructions on github worked fine to install. Thanks for the speedy responses!
