### ISSUE TITLE
Use with two-factor authentication

### ISSUE THREAD

**Issue by iSpeeX** [pbek/qownnotesapi#30]
Hello,

First of all, thanks for your great work with this API, it's a killer app !
I got a problem with the Qownnotes sync when i enable two factor authentication (here with Google Authenticator), can I do anything to make it work ? Or is it impossible ?

Thank you !

Best regards.

**Comment by pbek** [comment]
Thank you. ;)
Sure, see https://github.com/pbek/qownnotesapi/issues/25

**Comment by iSpeeX** [comment]
Oh crap... I don't know how I didn't find this issue ticket...
Sorry to bother you with my already-answered question !

Everything is working well again, thank you very much

**Comment by pbek** [comment]
No problem ;)
