### ISSUE TITLE
dependencies issue with recent upgrade to OC 10.2.1 on raspbian stretch with php7.2 

### ISSUE THREAD

**Issue by AWSBarker** [pbek/qownnotesapi#31]
I just upgraded my raspbian stretch OC server to 10.2.1 and during re-cloning of ownnotesapi I got and error in the OC web interface then at the CLI this:-
```
pi@raspberrypi3:/var/www/html/owncloud $ sudo -u www-data php occ app:enable qownnotesapi
In app.php line 1116:                                                                                                                          
  App "QOwnNotesAPI" cannot be installed because the following dependencies are not fulfilled: ownCloud 10.1 or lower is  
   required.                                                                                                                               
```
I see there is a php line so I wondered if was linked to upgrade to php7.2?

**Comment by pbek** [comment]
> I see there is a php line so I wondered if was linked to upgrade to php7.2?

Can't think of a reason why.
In https://github.com/pbek/qownnotesapi/blob/develop/appinfo/info.xml oC 11 is the maximum.
Did you alredy try to install qownnotesapi from the store?

**Comment by AWSBarker** [comment]
Thanks for feedback pbek, and by the way great work.

I saw that OC11 was mentioned hence my surprise at the fault.

I think the error is entirely mine, I forgot to disable qownnotes when upgrading and it must have left a fingerprint in the php files so I think I'll have to reinstall again.

If I still have problem after reinstall I come back.

**Comment by AWSBarker** [comment]
just to let you know, instead of reinstall OC I decided to try to to install your api from OC market place and it worked:-

> The connection was made successfully!
> Server version: 10.2.1.4
> QOwnNotesAPI version: 19.1.0  

Very robust. I'll live with the OC admin warnings about code integrity

**Comment by pbek** [comment]
Thank you for the kind words and great it works now. 😁
