### ISSUE TITLE
The newer version in ownCloud Marketrplace

### ISSUE THREAD

**Issue by cdamken** [pbek/qownnotesapi#32]
Hi I use the API and its great,

But (there is always a but ;) ) I had to download the newest version from Github and It would be great to download automatically from the Marketplace.

I hope you can upload it soon that way I can add in my server faster ;)

**Comment by pbek** [comment]
Thank you 😉 

There is no new version for ownCloud as you can see in the changelog https://github.com/pbek/qownnotesapi/blob/develop/CHANGELOG.md

**Comment by pbek** [comment]
If that that answers your question feel free to close the issue.
