### ISSUE TITLE
Nextcloud 17 support

### ISSUE THREAD

**Issue by nougad** [pbek/qownnotesapi#33]
Nextcloud 17 rc1 is released: https://nextcloud.com/blog/nextcloud-17-scales-up-and-improves-data-protection-with-remote-wipe-collaborative-text-editor-2fa-updates-ibm-spectrum-scale-support-and-global-scale-improvements/

It would be great if the app is supported on release date :)

**Comment by pbek** [comment]
Thank you for the notification. :)

**Comment by pbek** [comment]
Did you already test it with NC17?

**Comment by pbek** [comment]
I now released it for NC17: https://apps.nextcloud.com/apps/qownnotesapi
