### ISSUE TITLE
Installation fails on command line

### ISSUE THREAD

**Issue by christefano** [pbek/qownnotesapi#34]
Installation fails on Nextcloud 18.0.3 stable. 

```
$ git clone https://github.com/pbek/qownnotesapi.git apps/qownnotesapi -b master
Cloning into 'apps/qownnotesapi'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 474 (delta 9), reused 18 (delta 6), pack-reused 449
Receiving objects: 100% (474/474), 1.01 MiB | 7.34 MiB/s, done.
Resolving deltas: 100% (269/269), done.
$ ./occ app:enable qownnotesapi
App "QOwnNotesAPI" cannot be installed because it is not compatible with this version of the server.
```

Installation works from the Nextcloud app store, though! Confirmed with the QOwnNotes app on macOS:

```
The connection was made successfully!
Server version: 18.0.3.0
QOwnNotesAPI version: 20.1.0
```

**Comment by pbek** [comment]
I guess you need to try the develop branch if your really must install it on the cli. Is there a reason you don't want to use the nextcloud store?

**Comment by christefano** [comment]
> Is there a reason you don't want to use the nextcloud store?

I was just following the instructions in the README.md on the project page here in GitHub.

Like I said, installation works from the Nextcloud app store 🙂 I opened this issue because there seems to be either a bug or perhaps inaccurate documentation in the README.

**Comment by pbek** [comment]
Thank you, I updated the readme to use the develop branch (of course the integrity check will still fail).
