### ISSUE TITLE
Add compatibility for Nextcloud v23

### ISSUE THREAD

**Issue by rakekniven** [pbek/qownnotesapi#36]
v23 is already out.

**Comment by pbek** [comment]
Yes, I already wanted to update the app, but there isn't yet a docker image for NC 23 to test, so I need to wait.

**Comment by pbek** [comment]
Have fun!

## 21.12.0
- enabled and tested app for Nextcloud 23 (for [#36](https://github.com/pbek/qownnotesapi/issues/36))

**Comment by rakekniven** [comment]
The Nextcloud Project is beautiful, specially the app makers like you.

Vielen Dank 💟

**Comment by pbek** [comment]
Thank you very much, @rakekniven. 🙏🏻
