### ISSUE TITLE
Add compatibility for Nextcloud v24

### ISSUE THREAD

**Issue by roliverio** [pbek/qownnotesapi#38]
Hi!, please add compatibility with the recently released v24.

Thanks in advance and thanks for this app, works like a charm.

**Comment by pbek** [comment]
Thank you for mentioning.

**Comment by pbek** [comment]
## 22.5.0
- errors for not found files in the version API are now caught
- enabled and tested app for Nextcloud 24 (for [#38](https://github.com/pbek/qownnotesapi/issues/38))

There now is a new release, could you please test it and report if it works for you?

**Comment by rakekniven** [comment]
It works!

**Comment by pbek** [comment]
Great. I use it in production too already. 😉
