### ISSUE TITLE
notes server path not found

### ISSUE THREAD

**Issue by Tealk** [pbek/qownnotesapi#40]
Hello

the QOwnNotes app shows the following message:
![image](https://user-images.githubusercontent.com/12276250/195674830-91c1638f-f8e0-4b01-884a-b284f014cf02.png)

**Comment by pbek** [comment]
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by Tealk** [comment]
Sorry, I have overlooked that there is a Nextcloud path in the Note Folders, thought this is all set in Nextcloud.
