### ISSUE TITLE
Make app compatible with NC v25

### ISSUE THREAD

**Issue by rakekniven** [pbek/qownnotesapi#41]
Today NC25 is out and this app needs some love ❤️ .

**Comment by pbek** [comment]
I'm eagerly awaiting Nextcloud 25 on https://hub.docker.com/_/nextcloud to run my tests.

**Comment by pbek** [comment]
## 22.10.0
- the code got a cleanup
- enabled and tested app for Nextcloud 25 (for [#41](https://github.com/pbek/qownnotesapi/issues/41))

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
I already updated, works fine. ;)
