### ISSUE TITLE
Make app compatible with NC26

### ISSUE THREAD

**Issue by roliverio** [pbek/qownnotesapi#42]
Hi!, as soon as the Docker NC26 official image is out, please do a compatibility release. Thanks!

**Comment by pbek** [comment]
Thank you for mentioning

**Comment by roliverio** [comment]
Hi!

No, that's why i've mentioned "as soon as the official image is out", and not "i've already have the official image" ;-)

**Comment by pbek** [comment]
Ah, sorry. 😅

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?
