### ISSUE TITLE
Error message "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead."

### ISSUE THREAD

**Issue by mundschenk-at** [pbek/qownnotesapi#43]
With QOwnNotesAPI enabled, the NextCloud logfile is unfortunately constantly spammed with error messages about `"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead."` (reporting from NC26, but the API change happened some time ago).

**Comment by pbek** [comment]
I can't reproduce that on Nextcloud 26.0.2.
Could you please find out what you are doing in QOwnNotes to trigger that error? (Is it an error? Or just a notice or warning?)

**Comment by pbek** [comment]
Could it be that you have debug messages turned on?
See: https://github.com/nextcloud/server/issues/23046#issuecomment-708420457

I'd like to stay compatible with ownCloud and older versions of Nextcloud as long as possible...

**Comment by mundschenk-at** [comment]
Yeah, you are right, I've just noticed that I accidentally kept `loglevel` at `0` after debugging another issue.

**Comment by pbek** [comment]
## 23.6.0
- re-did the application structure for Nextcloud 27 (for [#43](https://github.com/pbek/qownnotesapi/issues/43))
- updated and tested app for Nextcloud 27 (for [#44](https://github.com/pbek/qownnotesapi/issues/44))
  - the min-version was raised to 22

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
And please tell me if you are also hit by #45...
