### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by SergioScabuzzo** [pbek/qownnotesapi#5]
I have OwnCloud 8.2.8
and qownnotesapi 16.09.0
When attempting to connect to my instance from QOwnNotes I get this message

index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/ - server replied: Not Acceptable
Looks like it's trying to access the / folder?

**Comment by pbek** [comment]
Thank you for reporting.
Maybe you haven't set the path to the Notes folder on your server.
Can you please post the output from the QOwnNotes debug settings.

**Comment by SergioScabuzzo** [comment]
Thanks for the quick reply!

Not sure how to "set the path" but I did tell OwnCloud to use the 
database and a "notes" folder in the admin settings.

QOwnNotes Debug Information

===========================

## General Info

**Current Date**: `Fri Oct 28 22:47:10 2016`

**Version**: `16.10.10`

**Build date**: `Oct 28 2016`

**Build number**: `256`

**Platform**: `linux`

**Operating System**: `Ubuntu 16.04.1 LTS`

**Build architecture**: `x86_64`

**Current architecture**: `x86_64`

**Release**: `Launchpad PPA`

**Qt Version (build)**: `5.5.1`

**Qt Version (runtime)**: `5.5.1`

**Portable mode**: `no`

**Qt Debug**: `0`

**Locale (system)**: `en_US`

**Locale (interface)**: *empty*

**Icon theme**: `breeze-dark`

**Notes in current note folder**: `3`

**Enabled scripts**: `0`

## Server Info

**serverUrl**: `http://domain.org/OwnCloud`

**appIsValid**: `no`

**connectionErrorMessage**: `Error downloading 
http://domain.org/OwnCloud/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/ 
- server replied: Not Acceptable`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`

**isCurrent**: `yes`

**activeTagId**: `0`

**localPath**: `/home/sergio/ownCloud/Notes`

**remotePath**: `Notes`

**isShowSubfolders**: `no`

**activeNoteSubFolder name**: *empty*

## Settings

**Editor/CurrentSchemaKey**: 
`EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`

**LastUpdateCheck**: `2016-10-28T22:46:58`

**MainWindow/geometry**: `<binary data>`

**MainWindow/mainToolBar.iconSize**: `22`

**MainWindow/menuBarGeometry**: `<binary data>`

**MainWindow/noteTextEdit.code.font**: `Oxygen Mono,9,-1,7,50,0,0,0,0,0`

**MainWindow/noteTextEdit.font**: `Noto Sans,10,-1,0,50,0,0,0,0,0`

**MainWindow/noteTextView.code.font**: `Oxygen Mono,9,-1,7,50,0,0,0,0,0`

**MainWindow/noteTextView.font**: `Noto Sans,10,-1,0,50,0,0,0,0,0`

**MainWindow/noteTextView.rtl**: `false`

**PiwikClientId**: `<hidden>`

**SettingsDialog/geometry**: `<binary data>`

**SettingsDialog/mainSplitterState**: `<binary data>`

**ShowSystemTray**: `false`

**SortingModeAlphabetically**: `false`

**WelcomeDialog/geometry**: `<binary data>`

**allowDifferentNoteFileName**: `false`

**allowOnlyOneAppInstance**: `false`

**appMetrics/disableAppHeartbeat**: `true`

**appMetrics/disableTracking**: `true`

**appMetrics/notificationShown**: `true`

**cryptoKey**: `<hidden>`

**currentNoteFolderId**: `1`

**currentWorkspace**: `b804e73f-91ca-4a1a-92d7-4da6bb3071db`

**customNoteFileExtensionList**: *empty*

**darkMode**: `false`

**darkModeColors**: `false`

**darkModeTrayIcon**: `false`

**defaultNoteFileExtension**: `md`

**demoNotesCreated**: `true`

**disableAutomaticUpdateDialog**: `false`

**dockWasInitializedOnce**: `true`

**externalEditorPath**: *empty*

**ignoreAllExternalModifications**: `false`

**ignoreAllExternalNoteFolderChanges**: `false`

**imageScaleDown**: `false`

**imageScaleDownMaximumHeight**: `1024`

**imageScaleDownMaximumWidth**: `1024`

**interfaceLanguage**: *empty*

**internalIconTheme**: `false`

**itemHeight**: `24`

**markdownHighlightingInterval**: `200`

**networking/ignoreSSLErrors**: `true`

**networking/proxyType**: `2`

**noteSaveIntervalTime**: `10`

**notesPath**: `/home/sergio/ownCloud/Notes`

**notifyAllExternalModifications**: `false`

**ownCloud/password**: `<hidden>`

**ownCloud/serverUrl**: `http://domain.org/OwnCloud`

**ownCloud/todoCalendarBackend**: `0`

**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`

**ownCloud/todoCalendarCalDAVServerUrl**: *empty*

**ownCloud/todoCalendarCalDAVUsername**: *empty*

**ownCloud/todoCalendarEnabledList**: *empty*

**ownCloud/todoCalendarEnabledUrlList**: *empty*

**ownCloud/todoCalendarUrlList**: *empty*

**ownCloud/userName**: `Sergio`

**previousWorkspace**: *empty*

**showMenuBar**: `true`

**showStatusBar**: `true`

**toolbar/1/items**: `action_New_note, action_Find_note, 
action_Remove_note, action_Open_note_in_external_editor, , 
action_Back_in_note_history, action_Forward_in_note_history, , 
action_Find_text_in_note, actionReplace_in_current_note, , 
actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`

**toolbar/1/name**: `mainToolBar`

**toolbar/1/title**: `main toolbar`

**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, 
actionStrike_out_text, actionInset_code_block`

**toolbar/2/name**: `formattingToolbar`

**toolbar/2/title**: `formatting toolbar`

**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, 
actionInsert_current_time`

**toolbar/3/name**: `insertingToolbar`

**toolbar/3/title**: `inserting toolbar`

**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, 
actionDecrypt_note`

**toolbar/4/name**: `encryptionToolbar`

**toolbar/4/title**: `encryption toolbar`

**toolbar/5/items**: `actionWorkspaceComboBox, 
actionStore_as_new_workspace, actionRemove_current_workspace, 
actionRename_current_workspace, actionSwitch_to_previous_workspace, 
actionLock_panels, , actionToggle_distraction_free_mode, 
action_Increase_note_text_size, action_Decrease_note_text_size, 
action_Reset_note_text_size`

**toolbar/5/name**: `windowToolbar`

**toolbar/5/title**: `window toolbar`

**toolbar/6/items**: `action_Quit`

**toolbar/6/name**: `quitToolbar`

**toolbar/6/title**: `quit toolbar`

**toolbar/size**: `0`

**workspace-b804e73f-91ca-4a1a-92d7-4da6bb3071db/name**: `default`

**workspace-b804e73f-91ca-4a1a-92d7-4da6bb3071db/noteSubFolderDockWidgetVisible**: 
`true`

**workspace-b804e73f-91ca-4a1a-92d7-4da6bb3071db/windowState**: `<binary 
data>`

**workspaces**: `b804e73f-91ca-4a1a-92d7-4da6bb3071db`

Sergio Scabuzzo Certified: Water harvester Permaculture designer 
Greywater systems installer/educator (818)339-3420 <tel:8183393420> 
www.thegreenmanproject.com <http://www.thegreenmanproject.com>

**Comment by pbek** [comment]
<http://domain.org/OwnCloud/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/> doesn't exist. Nor does <http://domain.org/OwnCloud/index.php>...

Are you sure that's the url to your ownCloud server?

**Comment by pbek** [comment]
I will close this issue until there is more information.

**Comment by SergioScabuzzo** [comment]
Sorry, been out of town. I changed the domain, didn't think it mattered. Instead of domain.org it's earthshaper.org

http://earthshaper.org/OwnCloud/index.php

http://earthshaper.org/OwnCloud/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/

**Comment by pbek** [comment]
please try using `http://earthshaper.org/OwnCloud/` as server url

**Comment by pbek** [comment]
if that doesn't help I guess I will need a test account on your server...

**Comment by SergioScabuzzo** [comment]
It does not work. After clicking on the connect button, it auto removes the /
Also, when I click on the "Open your ownCloud server Apps page" it takes me to my page. So the link is valid.

This is the original error message:
Connection error message: Error transferring http://earthshaper.org/OwnCloud/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/Notes/ - server replied: Not Acceptable

If I try this link on my browser, logged in to ownCloud, it responds with this:
{"message":"CORS requires basic auth"}

This looks like might solve the problem:
https://github.com/Fmstrat/ownnote/issues/174

**Comment by pbek** [comment]
So the app wasn't enabled and you were able to fix that now?

**Comment by SergioScabuzzo** [comment]
No, still not working. 
I'm assuming that the issue might be related to the CORS implementation being changed since this was last updated... https://github.com/Fmstrat/ownnote/issues/174
This is from the above link:
"Looks like they changed the CORS implementation again. It's frustrating that everytime a new OC version rolls around they break the API. A good change on their part for security, but I really wish there was a system for announcements (or maybe there is and I'm unaware of them)."
Though I could be wrong as I know next to nothing on this subject...

**Comment by SergioScabuzzo** [comment]
Wait!
Problem changed. It now works, but the Desktop side still tells me:
"Cannot connect to your ownCloud server! Please check your ownCloud configuration."

Though the notes are syncing...

**Comment by pbek** [comment]
Are you sure you entered your username and password correctly (especially the correct case)? If you create me an account I'll take a look at it...
Notes are supposed to be synced with your ownCloud sync client.

**Comment by pbek** [comment]
I tried the account and got the same error message. It almost seams that the version of ownCloud is not the same as the original one... I have to play around with it some more...

**Comment by pbek** [comment]
When I try a webdav request on <http://earthshaper.org/OwnCloud> I get a `405 - Method not allowed` error.

But a get request on <http://earthshaper.org/OwnCloud/index.php/apps/qownnotesapi/api/v1/note/app_info?format=json&notes_path=/> worked...

```
{
  "versions_app": true,
  "trash_app": true,
  "versioning": true,
  "app_version": "16.09.0",
  "server_version": "8.2.8.2",
  "notes_path_exists": true
}
```

Strange...

**Comment by pbek** [comment]
I also got some errors like:
`An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.`

I think your ownCloud provider or server hoster might have blocked some requests...

**Comment by pbek** [comment]
And also requests to <http://earthshaper.org/OwnCloud/ocs/v1.php> are failing...

**Comment by SergioScabuzzo** [comment]
Bluehost is hosting it on a shared server. Wonder if that's it. I'll be looking to move to Digital Ocean soon, so I'll have full control. The strange this is that it works, only problem is that the program is telling me it's not every time I start it up.

**Comment by pbek** [comment]
When you are removing your ownCloud server settings you shouldn't get the error again.
