### ISSUE TITLE
API not listed as available in Nextcloud

### ISSUE THREAD

**Issue by putt1ck** [pbek/qownnotesapi#6]
Looking at deploying QOwnNotes for a client, so need to document process/decision tree etc.. Cannot find a listing for the API on Nextcloud App store e.g. an equivalent of https://apps.owncloud.com/content/show.php?content=173817 - which might make client uncomfortable. 

Is it likely the API package will be listed on Nextcloud or is the situation different in their setup?

**Comment by pbek** [comment]
Last time I tried to submit QOwnNotesAPI the Nextcloud store was broken. I will try again... Previously I think they included the apps from the ownCloud apps page. I guess they stopped doing that now...

**Comment by pbek** [comment]
Still the same issue, `QOwnNotesAPI` isn't accepted as name on <https://apps.nextcloud.com/developer/apps/generate>. :(

**Comment by putt1ck** [comment]
Any similar issues at https://github.com/nextcloud/appstore/issues ? Or on the forums?

**Comment by pbek** [comment]
I asked on IRC but got no answer yet, I now posted an issue at <https://github.com/nextcloud/appstore/issues/385>.

**Comment by pbek** [comment]
I think <https://apps.nextcloud.com/developer/apps/generate> is not needed at all. Seems like I have to invest more time in reading how to actually post an app to the Nextcloud store.

**Comment by pbek** [comment]
Yesterday I created a certificate for QOwnNotesAPI and made a pull request to get it signed.

**Comment by pbek** [comment]
Nextcloud doesn't allow the versioning schema I use. :)
I created an other issue to ask about that.
<https://github.com/nextcloud/appstore/issues/393>

**Comment by pbek** [comment]
@putt1ck, the app is now finally in the Nextcloud app store.
<https://apps.nextcloud.com/apps/qownnotesapi>

Please report if you have any troubles using it.
