### ISSUE TITLE
Support for Nextcloud 11?

### ISSUE THREAD

**Issue by x86dev** [pbek/qownnotesapi#7]
Just upgraded my Nextcloud instance from Nextcloud 9 to 11.0, and when installing the "
QOwnNotesAPI" on the Apps page gives me the following error:

"App "QOwnNotesAPI" cannot be installed because the following dependencies are not fulfilled: Server version 9.2 or lower is required."

Did anything change wrt the API you need to tweak first, or is just a version bump required?

Keep up the good work!

**Comment by pbek** [comment]
Thank you, @x86dev.
Did you install it from <https://apps.nextcloud.com/apps/qownnotesapi>? In NC11 QOwnNotesAPI should be directly available in the app store, best just remove it and install it again...

Does that solve your problem?

**Comment by x86dev** [comment]
Yes, that did the trick! I was having a git pull in my apps2 directory, and that apparently did not go too well with NC11. Thanks for the hint! Closing.

**Comment by pbek** [comment]
Great!
