### ISSUE TITLE
Integrity check fails due to missing .editorconfig

### ISSUE THREAD

**Issue by JoshStrobl** [pbek/qownnotesapi#8]
Integrity check fails on Nextcloud 10.0.2 with qownnotesapi reflecting `master`, running `sudo -u www-data php occ integrity:check-app qownnotesapi` with the following output:

``` bash
Results
=======
- qownnotesapi
	- FILE_MISSING
		- .editorconfig

Raw output
==========
Array
(
    [qownnotesapi] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.editorconfig] => Array
                        (
                            [expected] => 3f6603e83dd948fb07946fd9fee11673c1196a3e3710a6b5dfd2f8861a3cfd49a8abca1273f9678f529d0c2edca9fd3f6d51adc07bcd071f9aa0716075f7e048
                            [current] => 
                        )

                )

        )
```

Result of `.editorconfig` being set in `.gitignore`

**Comment by pbek** [comment]
Can you please test (and use) the latest release from <https://github.com/pbek/qownnotesapi/releases>.

**Comment by JoshStrobl** [comment]
Can confirm that the tarball ships with .editorconfig, thus resolving the integrity check. Didn't really cross my mind to try the tarball, given the Installation instructions on the README state to clone the repo:

``` markdown
Clone the app into your Nextcloud / ownCloud apps directory:

git clone https://github.com/pbek/qownnotesapi.git apps/qownnotesapi -b master
```

**Comment by pbek** [comment]
Yes, I'm sorry. The signing process for ownCloud AND Nextcloud (that uses a different mechanic from NC 11 up) is very tricky...

**Comment by JoshStrobl** [comment]
No problem. Haven't upgraded to NC 11 yet so wasn't aware NC 11+ used a different mechanism. Haven't upgraded since it requires PHP 5.6 and my server is running Ubuntu 14.04.5 (thus using PHP 5.5), dist-upgrades between LTSes are always a PITA :smile:

If there are no actionable items for this issue, you're welcome to close it.

**Comment by pbek** [comment]
Server upgrades always are a PITA...

NC 11 uses their own app store.
https://apps.nextcloud.com/apps/qownnotesapi
